#!/bin/tcsh -e

raco make summer-school.scrbl

zip -r ql.zip ql/*.rkt ql/*.ql

scribble --htmls ++xref-in setup/xref load-collections-xref \
         --redirect-main "http://docs.racket-lang.org/docs/html/" \
          --dest Tmp/ \
          summer-school.scrbl 

echo 'done'
open Tmp/summer-school/index.html
