#!/bin/tcsh 

cp plan.scrbl summer-school.scrbl

scribble --htmls ++xref-in setup/xref load-collections-xref \
#          --redirect-main "http://pre.plt-scheme.org/docs/html/" \
#  "http://docs.plt-scheme.org/" \
          --dest ../../../0Unison/0Web/ \
          summer-school.scrbl 

echo 'done'
open ../../../0Unison/0Web/summer-school/index.html
