#!/bin/tcsh 

scribble --htmls ++xref-in setup/xref load-collections-xref \
          --redirect-main "http://docs.plt-scheme.org/" \
          --dest /Users/matthias/0Unison/0Web/ \
          summer-school.scrbl 

echo 'done'
open ../../../0Unison/0Web/summer-school/index.html
